version : "3.2"

services:
  jenkins:
    image : jenkins/jenkins:2.541.1-lts
    container_name: test-jenkins
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

